[package]
name = "txkillswitch"
version = "0.1.0"
authors = ["Veelkoov <veelkoov@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
getopts = "0.2"
